name: flutter_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.1.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  talker: ^4.7.1
  talker_riverpod_logger: ^4.7.1
  talker_flutter: ^4.7.1
  splash_master: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/

splash_master:
  # Use to specifies the color for the splash screen
  color: '#FFFFFF'
  # Use to specifies the splash image
  image: 'assets/images/splash/splash.png'
  # Provides content mode for splash image in iOS
  # iOS content mode options: scaleToFill, scaleAspectFit, scaleAspectFill, redraw, center, top, bottom,
  # left, right, topLeft, topRight, bottomLeft, bottomRight.
  ios_content_mode: 'center'
  # Provides gravity for splash image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  android_gravity: 'center'
  # Use to specifies the splash image
  background_image: 'assets/images/splash/background_image.png'
  # Provided content mode for splash image in background for iOS
  ios_background_content_mode: 'scaleToFill'
  # Provides gravity for background image in Android
  # Android gravity options: center, clip_horizontal, clip_vertical, fill_horizontal, fill, center_vertical, 
  # bottom, fill_vertical, center_horizontal, top, end, left, right, start
  android_background_image_gravity: 'fill'
  # Use to specifies image for android in dark mode
  image_dark_android: 'assets/images/splash/splash_dark.png'
  # Provides gravity for splash image for Android in dark mode
  android_dark_gravity_key: 'center'
  # Use to specifies the color for the splash screen for Android in dark mode
  color_dark_android: '#000000'
  # Section to specifies the configuration for the splash in Android 12+
  android_12_and_above:
    # Provides the background color of splash screen
    color: '#FFFFFF'
    # Provides custom icon to replace the default app icon
    image: 'assets/splash_12.png'
    # Provides branding image which is shown under main icon image. 
    branding_image: 'assets/images/splash/branding_image.png'
