name: flutter_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^4.1.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  talker: ^4.7.1
  talker_riverpod_logger: ^4.7.1
  talker_flutter: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
